theme: jekyll-theme-midnight
title: Welcome to Tyler Dukes' Software Development Portfolio!
description: Placeholder

##Code Review
[Raspberry Pi weather station and matrix calculator](https://youtu.be/6oifykWsmmU)
